name: simulated_annealing

description: Simulated annealing framework for finding the global minimum of
  multi-variate functions.

version: 0.4.0

homepage: https://github.com/simphotonics/simulated_annealing

topics:
 - simulated-annealing
 - global
 - minimum
 - multi-variate

environment:
  sdk: '^3.0.0'

dependencies:
  exception_templates: ^0.3.1
  lazy_memo: ^0.2.3
  list_operators: ^0.5.0

dev_dependencies:
  lints: ^4.0.0
  matcher: ^0.12.16+1
  test: ^1.25.5
