name: simulated_annealing

description: Simulated annealing framework for finding the global minimum of
  multi-variate functions.

version: 0.4.1

homepage: https://github.com/simphotonics/simulated_annealing

topics:
  - simulated-annealing
  - global-minimum
  - multi-variate

environment:
  sdk: '^3.9.0'

dependencies:
  exception_templates: ^0.3.2
  lazy_memo: ^0.2.5
  list_operators: ^0.5.1

dev_dependencies:
  lints: ^6.0.0
  matcher: ^0.12.17
  test: ^1.26.3
