name: simulated_annealing

description: Simulated annealing framework for Dart. Enables quickly setting up
  a simulator for finding the global minimum of multi-variate functions.

version: 0.2.2

homepage: https://github.com/simphotonics/simulated_annealing

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.0
  lazy_memo: ^0.1.2
  list_operators: ^0.2.8

dev_dependencies:
  matcher: ^0.12.10
  pedantic: ^1.11.0
  test: ^1.16.8
