name: simulated_annealing

description: Simulated annealing framework for Dart for
  finding the global minimum of multi-variate functions.

version: 0.3.4

homepage: https://github.com/simphotonics/simulated_annealing

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.4
  lazy_memo: ^0.1.3
  list_operators: ^0.3.7

dev_dependencies:
  lints: ^2.0.1
  matcher: ^0.12.14
  test: ^1.23.1
